### ISSUE TITLE
 name 'tempid' is not defined

### ISSUE THREAD

**Issue by HelloWorld-LTY** [hiddenblue/Pubmedsoso#12]
靓仔你好！感谢你的开发！！但我现在遇到个问题不知道怎么解决，我是在win11系统使用的，测试下载的时候报错：
2024-12-17 09:24:24,190-Pubmed-INFO- dbpath: pubmedsql
2024-12-17 09:24:24,190-Pubmed-INFO- tablename: pubmed20241217092408
2024-12-17 09:24:24,192-Pubmed-INFO- 读取sql信息成功 数据类型为PMCID和doctitle

2024-12-17 09:24:24,194-Pubmed-INFO- 开始下载第 0-1篇
Error occured: name 'tempid' is not defined
Traceback (most recent call last):
  File "E:\PycharmProject\00Deeplearning\01catchliterature\Pubmedsoso\utils\PDFHelper.py", line 151, in PDFdownloadAsync
    medLog.info("%s.pdf 从目标站获取pdf数据成功" % tempid)
NameError: name 'tempid' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PycharmProject\00Deeplearning\01catchliterature\Pubmedsoso\main.py", line 193, in <module>
    PDFHelper.PDFBatchDownloadEntry(args.downloadnum)
  File "E:\PycharmProject\00Deeplearning\01catchliterature\Pubmedsoso\utils\PDFHelper.py", line 98, in PDFBatchDownloadEntry
    pdf_list: [Optional[bytes]] = asyncio.run(cls.PDFBatchDonwloadAsync(target_pmcid_list))
  File "E:\python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\PycharmProject\00Deeplearning\01catchliterature\Pubmedsoso\utils\PDFHelper.py", line 135, in PDFBatchDonwloadAsync
    results = await asyncio.gather(*tasks)
  File "E:\PycharmProject\00Deeplearning\01catchliterature\Pubmedsoso\utils\PDFHelper.py", line 161, in PDFdownloadAsync
    medLog.error("%s.pdf 从目标站获取pdf数据失败" % tempid, )
NameError: name 'tempid' is not defined

谢谢！

**Comment by HelloWorld-LTY** [comment]
你好！我尝试解决了一下，主要是修改了PDFHelper.py里面的代码，添加了get_tempid_by_pmcid函数，把free_pmc_list 保存为类的成员变量，还把async def PDFdownloadAsync中的medLog代码中的tempid换成tempid.PMCID，具体修改的如下：
    def __init__(self, dbpath):
        self.dbpath = dbpath
        self.free_pmc_list = []

    @classmethod
    def get_tempid_by_pmcid(cls, PMCID: str) -> TempPMID:
        for item in cls.free_pmc_list:
            if item.PMCID == PMCID:
                return item
        raise ValueError(f"PMCID {PMCID} 对应的tempid未找到")

    def PDFBatchDownloadEntry(cls, limit):
        """
        异步批量处理的pdf下载函数
        感觉写得稀烂啊
        """
        tablename = 'pubmed%s' % projConfig.savetime
        dbpath = 'pubmedsql'
        # 注意这个列表的数据类型，和名称并不是相符的
        # 这个返回的结果是有免费全文的，包括 FreeArticle 和 FreePMCArticle 两类
        free_article_list: [TempPMID] = DBFetchAllFreePMC(dbpath, tablename)

        cls.free_pmc_list = [item for item in free_article_list if item.PMCID != ""]

        # 过滤掉已经存在于本地的文献
        target_pmc_list: [TempPMID] = []  # target pdf list to be downloaded

        for item in cls.free_pmc_list:
            if cls.__IsPDFExist(item):
                # 存在于目录当中直接更新就行了
                cls.PDFUpdateDB(item, cls.__GetPDFSavePath(item), dbpath)
                medLog.info(f"PDF: {cls.__GetPDFFileName(item)} 在保存目录当中已存在，跳过下载")
                # 还没有下载就放到待下载列表当中
            else:
                target_pmc_list.append(item)

    async def PDFdownloadAsync(cls, session: ClientSession, PMCID: str) -> Optional[bytes]:
        downloadUrl = cls.baseurl + "pmc/articles/" + PMCID + "/pdf/main.pdf"
        semaphore = asyncio.Semaphore(5)

        tempid = cls.get_tempid_by_pmcid(PMCID)

        async with semaphore:
            try:
                response = await session.get(downloadUrl, headers=cls.headers)
                content = await response.read()
                medLog.info("%s.pdf 从目标站获取pdf数据成功" % tempid.PMCID)
                return content

            except (aiohttp.ClientResponseError, aiohttp.ClientHttpProxyError) as e:
                cls.handle_error(e)
                medLog.error("%s.pdf 从目标站获取pdf数据失败" % tempid.PMCID)
                return None

            except Exception as e:
                cls.handle_error(e)
                medLog.error("%s.pdf 从目标站获取pdf数据失败" % tempid.PMCID)
                return None

**Comment by hiddenblue** [comment]
刚看了，其实PDFdownloadAsync这块函数是执行单个文献下载的，日志打印的时候直接输出PMCID信息就行了（早期是通过tempid来输出的），加日志系统的时候忘了改了🤔

 由于下面if__ name__那块定义了同名的变量，导致IDE没法检查出来这个错误。

修复后的版本 #

```py
    @classmethod
    async def PDFdownloadAsync(cls, session: ClientSession, PMCID: str) -> Optional[bytes]:
        downloadUrl = cls.baseurl + "pmc/articles/" + PMCID + "/pdf/main.pdf"
        semaphore = asyncio.Semaphore(5)

        async with semaphore:
            try:
                response = await session.get(downloadUrl, headers=cls.headers)
                content = await response.read()
                medLog.info("%s.pdf 从目标站获取pdf数据成功" % PMCID)
                return content

            except (aiohttp.ClientResponseError, aiohttp.ClientHttpProxyError) as e:
                cls.handle_error(e)
                medLog.error("%s.pdf 从目标站获取pdf数据失败" % PMCID)
                return None

            except Exception as e:
                cls.handle_error(e)
                medLog.error("%s.pdf 从目标站获取pdf数据失败" % PMCID, )
                return None
```
